### PR TITLE
Created Readme.md

### PR DESCRIPTION
**Pull request by Anshu-Bijarnia**
Closes https://github.com/this-Aditya/BlogPosts/issues/2

Added necessary images in the images folder and apk of current build in the Apk folder for readme file along with the README.md file itself.

### CODE REVIEW

**Comment by this-Aditya** [comment]
Looks good to me

**Comment by this-Aditya** [comment]
That's nice work, Anshu. As I mentioned this project is in progress and creating and needs some updates. Will it be fine if I notify you when this is completed So that a new apk file can be added?

**Comment by Anshu-Bijarnia** [comment]
Yeah sure, you can let me know when it is completed, i will update the apk
and do some necessary changes to the README.md

**Comment by this-Aditya** [comment]
Ya, I will notify you.

**Pull request merged**
